# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

apply = ['defer']

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.fzf]
github = "junegunn/fzf"
apply = ['fzf-install', 'fzf-source']

[plugins.anyframe]
github = "mollifier/anyframe"
apply = ['source']

#[plugins.zsh-vi-mode]
#github = "jeffreytse/zsh-vi-mode"

[plugins.autoenv]
github = "Tarrasch/zsh-autoenv"

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n[[ ! $PATH =~ {{ dir }} ]] && export PATH=\"$PATH:{{ dir }}/bin\"\n"
fzf-source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"
