format = '''$directory$time$python${custom.dis_no}
$character'''

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bright-blue"

[time]
disabled = false
style = "bright-yellow"
format = '[\[$time\]]($style) '
time_format = '%H:%M'

[python]
format = '[\($virtualenv\)]($style)'
style = "bright-green"

[custom.dis_no]
command = "LANG=C export | grep 'DISPLAY' | awk -F: '{print $2}'"
when = true
format = ' [\[$output\]]($style)'
style = "bright-purple"

