format = '''$directory$time$python$cmd_duration
$character'''

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bright-blue"

[time]
disabled = false
style = "bright-yellow"
format = '[\[$time\]]($style) '
time_format = '%H:%M'

[cmd_duration]
style = "yellow"
format = '[\[$duration\]]($style) '

[python]
format = '[\($virtualenv\)]($style) '
style = "bright-green"

[character]
vimcmd_symbol = '[❮](bold blue)'
vimcmd_visual_symbol = '[❮](bold yellow)'

[custom.dis_no]
command = "LANG=C export | grep 'DISPLAY' | awk -F: '{print $2}'"
when = true
format = ' [\[$output\]]($style)'
style = "bright-purple"

